library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity Top_CUTECAR is
  port (
    CLOCK_50 : in  std_logic;
    KEY      : in  std_logic_vector(0 downto 0);
    SW       : in  std_logic_vector(7 downto 0);
    LED      : out std_logic_vector(7 downto 0);

    -- SDRAM interface
    DRAM_CLK   : out std_logic;
    DRAM_CKE   : out std_logic;
    DRAM_ADDR  : out std_logic_vector(12 downto 0);
    DRAM_BA    : out std_logic_vector(1 downto 0);
    DRAM_CS_N  : out std_logic;
    DRAM_CAS_N : out std_logic;
    DRAM_RAS_N : out std_logic;
    DRAM_WE_N  : out std_logic;
    DRAM_DQ    : inout std_logic_vector(15 downto 0);
    DRAM_DQM   : out std_logic_vector(1 downto 0);

    -- Motor outputs
    MTRR_P : out std_logic;
    MTRR_N : out std_logic;
    MTRL_P : out std_logic;
    MTRL_N : out std_logic
  );
end entity Top_CUTECAR;


architecture rtl of Top_CUTECAR is

  signal pwm_motor_out : std_logic_vector(3 downto 0);

  component Nios_CUTECAR is
    port (
      clk_clk                                              : in    std_logic;
      switches_export                                      : in    std_logic_vector(7 downto 0);
      leds_export                                          : out   std_logic_vector(7 downto 0);

      sdram_wire_addr                                      : out   std_logic_vector(12 downto 0);
      sdram_wire_ba                                        : out   std_logic_vector(1 downto 0);
      sdram_wire_cas_n                                     : out   std_logic;
      sdram_wire_cke                                       : out   std_logic;
      sdram_wire_cs_n                                      : out   std_logic;
      sdram_wire_dq                                        : inout std_logic_vector(15 downto 0);
      sdram_wire_dqm                                       : out   std_logic_vector(1 downto 0);
      sdram_wire_ras_n                                     : out   std_logic;
      sdram_wire_we_n                                      : out   std_logic;

      reset_reset_n                                        : in    std_logic;
      clocks_sdram_clk_clk                                 : out   std_logic;

      pwm_generation_avalon_interface_0_conduit_end_export : out   std_logic_vector(3 downto 0)
    );
  end component Nios_CUTECAR;

begin

  u0 : Nios_CUTECAR
    port map (
      -- Clock and reset
      clk_clk       => CLOCK_50,
      reset_reset_n => KEY(0),

      -- Switches and LEDs
      switches_export => SW,
      leds_export     => LED,

      -- SDRAM physical interface
      sdram_wire_addr  => DRAM_ADDR,
      sdram_wire_ba    => DRAM_BA,
      sdram_wire_cas_n => DRAM_CAS_N,
      sdram_wire_cke   => DRAM_CKE,
      sdram_wire_cs_n  => DRAM_CS_N,
      sdram_wire_dq    => DRAM_DQ,
      sdram_wire_dqm   => DRAM_DQM,
      sdram_wire_ras_n => DRAM_RAS_N,
      sdram_wire_we_n  => DRAM_WE_N,

      -- SDRAM clock generated by Qsys
      clocks_sdram_clk_clk => DRAM_CLK,

      -- PWM motor conduit vector
      pwm_generation_avalon_interface_0_conduit_end_export => pwm_motor_out
    );

  --------------------------------------------------------------------
  -- Mapping of the 4-bit conduit to physical motor outputs
  --------------------------------------------------------------------
  -- pwm_motor_out(3) = right motor positive
  -- pwm_motor_out(2) = right motor negative
  -- pwm_motor_out(1) = left motor positive
  -- pwm_motor_out(0) = left motor negative

  MTRR_P <= pwm_motor_out(3);
  MTRR_N <= pwm_motor_out(2);
  MTRL_P <= pwm_motor_out(1);
  MTRL_N <= pwm_motor_out(0);

end architecture rtl;